# Generated by Django 2.2.5 on 2019-09-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alerts_lifetime',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
