# Generated by Django 2.2.5 on 2019-09-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190913_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
