# Generated by Django 2.2.5 on 2019-09-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20190913_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='user_id',
            new_name='user',
        ),
    ]
